# Don't touch
version: 1

folder:
  # Root template folder
  templates: templates

  # Cache folder
  cache: cache

  # Servers folder
  instances: servers

# Server Config
bungeecord:
  ip-listen: 127.0.0.1

  # Start of Dynamic Ports
  port-start: 26000

  # How many ports to reserve
  port-amount: 1000
